# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for SOS
	pod 'IQKeyboardManager'
 	pod 'SwiftyJSON'
 	pod 'Alamofire', '~> 4.4'
 	pod 'GoogleMaps'
	pod 'GooglePlaces'
 	pod 'SJSegmentedScrollView'
 	pod 'ImageSlideshow/Kingfisher’
 	pod 'KRProgressHUD'
    pod 'UITextView+Placeholder'
    pod 'Kingfisher'

end
